workflows:
  native-android:
    name: Native Android
    instance_type: mac_pro
    environment:
      vars:
        # Android Keystore environment variables
        CM_KEYSTORE: Encrypted(Z0FBQUFBQmcwal9SNUppYks5ZXlMdC1LWTZPaHIwal9sUGEzb1d3QzU3bEdoQ1VhdU1FcWJsRVg3Rk1wRUpqYnJ4Sm9QNkxVUnZsY3VGREs4TnUzQkdUYkllYTNyRVFiMFlUQ1hCT1BoT0w0eDMyUTZqSG1ucHA2VGZrWDJWYWhlYlBUeVZ6U1Flak1OaDJaQmQ4NHQ2R1BlcFhXRE1GYjRtYXVHaWVKZHlZODVfWGxDa3ZvXzFYNU83aWtxOEJZT1J6MnZyWFFyT2x2RTFHM3dBQ0JaOUtBQi1VbWNUMU0zaktOeHIzV3BxUHVFXzFhbm1mQ25zNWJ1cjBFXzVKTXNWTVhyMnVPN3U0MnltOW4walhNX1ZNMFFuQWQzbDlfQnQyRXZJbDZkY0prNDY5MldaYWtXYTBZVVJnRmJXY29DWkNHWTM1VF9uNVZOWlFKTWpXSG82LV9CYzVPTWlWWXJ6VUc4LUJrdTZWMDZDWGNYRUx5aXJJc19CVFhXdGlRNXdmejVxTGZYMzdkSXFucWViODdLR3huVUVSanVPR2pCSi1DQXl6czYtTUZraG9jdFZGTkM1WExrVzBISHNqckJ6VHpQaFotaG16a1k4YWRWN19UMVlUcUt2Sy1JNEtCWFluTjFMM1ZNNnpBbEhsREc4WkxSNzlQOC01c0xoSHVGbUlfU0ZORXdsTW9NWndGeDB1MW1sYUsySHQ3NXdfa2xWSVpwaFVGRmZuczUzV3oxb0k0WkNNUjc4bXcxMXVsRV9fUjVZLTI4ZGYzSXozQkY0a09BdTRUZFgtS1k1NlZHSm5DQ0FabmhWY0Y5UHNCeGFGR2hrWmhlNGxERy1oaG9qYXR1U1Z6Rk9YMW8zb29wVXJnaGRRUlFpQkFZd096eURkc25GdUlDUmRkX2JIRHItRjNpT1oxZFFUY0RVc2xLbHZKLW1tT2pNVnMybTlsT1VXRHN4SUZRNkNfX0tGeXphOW1nT1hzcHFCVzFmZVVBeTZzSTA1QXpDNHB1ZXhpOVUtOVItRE1RZnAtTFNTbmZ6NGFyYWo2WDJqa2lONlVWX1MzZVB4eDVyRkd6TktmWVVBblU0TDUtSWkya2w2UTJOUTBjMkh1d3FkSVRNOTZYVlcyUGgxUEJiUnRHMUVrWmszdHctNmx0OGlKMGpmeXloSHZscTdSTzFrY1F5a0NvbVMwLThHakVXNmVMYVFteUlyRVdaTHNEcmg3T1Q2S19xVEwyTXh4Zm42eHgzazFXTFZMMy1oMFdwWEcxbVc1ZFc2Z1Jxay04Nk5QRk1vdUxLNFBCY213Sm9BS1hnR2MwcUVSQkpSZ2tIWTJGRlBjZUo1SXZLUVVaNVJmU2RoaTBIVklucmduYXcweUxVZGI2TXdzZl9WanFNNGFFZG5BUGtFLUg4amlaNlFMay12RDBmVm5waGx0eFJmZUE2MTVfZUNBd20yOVZidXRKZ19VT18yT1EyMHlCSmc4M3lsRkVsOHM5cXZmVWszRlgwVXVjNkpwTkJEdzBhWm45N21GdnhrRUY1clVHamlpd1hSZkRZTXRrczV3MlBZcldOdlV6Zy1FcmJXcnZJYi1hMVRWNjR5eElJUXVtRkFjbmtVMU53LXI2eFBxUm83cW5lZmpoWGJsNFlfbVJLVV9HT0drM1VtQWJJUl9qZFhPZTY3aW52RDQzZ1F5SEpmTG5SejFwRS04R2xLa0ZGTy1KdDZJX0lEWFZUZDRSSmNVVHI5cFNtN05ua2xBQXJ4OENuQ3FYcE5CT1FEQmFPbTI0TG1jY1VMYm5SZzBrWDMxQ2VZZi10bFZoQWJnUUVkc2pnR0k3c0tyYnV4Z1g0d2NBRnZEVjVKdVZ2LVBRSkdWcUdaam1xWHNyUDMwbXhtY3lXbXFxbTE2Vktzd0g4Yzg2WGNSempDVTBacURITUgxbkkyVERHcUNndUdpTXNES1p2WkZmV1Blc3I2SmpqV085REI2ajVFa3RyMmNGbHVrcU9VZk4zM2JqSlZ4WVgtLXJFdXRRWDIwWnRGTUp3Vk5QbmZIUDVuS1Q3bFlqMXB6SldxRXY0bUlIR25IclB4YkpKTUJGVnA0Y2VkRHhaMFMtbWhfYmdwOTc5U1dOV0VGWXlHVXlGWG1kMGxOcHpnYktFZUZkcFhpRlhVTVE0RzBJWmFBekI1TzJtamhweE5Hb0poWjFBMjBmYmhwOFR2YWZkTkZiSEtSN28zSy1zODBXY2wtM0dueV9zaGZPWkh5STRkS3MxT2ItMF9GUGhrZ3U3VGNOdmVra1Zka2h6MUpiTTJEOXYxMmw0cFlGZFR1b0FucXVRYzVBUnRvUlk3d2VXbXVGNkpzY2V5T2NSVkRnbW1Td2pub0ZOU0l5dVRPUE9HSU9CdGlIYkdROXNyclo5TjVwcDMwSFp3dkY0WVF1Y3M4YXYzRWhNY2l2NDNoeU5OVVRUMEVqNzdvRkg5YXhDQk91aHdERjhoS05Oa0ItU3UzcFItNUxUTkduQW5BMXNIV1VXdWhfRENESzB0dzRSUW54anJmdmY3ZFNDaER3Z0pLVXR2RnRBaGY3eUJQRUhUM1JWZ3ZwXy1ZQlZWaWl0ckgtUm1RLVE3M2ZWbmxoWEM4V2JyanlYSHZGanZwYURMSUJ3d3pCdzZ0eG9XaUVsVjROMDlpeC13TXlvcnYxVEY0VmN4MUpjR3VhdTU1b242b2pRR2hGNENMQlpNbHBlejZKT1l3TVQ1a01GWHlJQzVya0JXN1dnVGIyb0tzNk5qcXh0UHoxdktpLU9CNUNnTTZ1dEx2RjEyYk9MU18yMzJ1S2U1XzUydHA0YlBidGZ4cG5yV3RpOS1MUlRmaUVaQ0kwRlQ0SmRTY3NvNkxkR1JabzJVWlhfOVJROXJCV2pQVnFZNjBkOHB3MUVmRExPOERWWE1TaGc1ODZrTmhGMmVFNmFFV3NSTGRzQnlwS2tTWENEd1RSdmYtOW5TMnEyZDdpTnFVOHRPUV9BQzcwaHFRNnpjb2kzejdkSzkxOGVnNDJBNC1mVTlIZU14ek4xd3l1WDVTeDMwRFdRdTByZjRRWXBibVo3VVAyeThhcmNlWjQzQUI4OV8xLW5IZ2VTal9mWnRwczdDZV90dlZlaXdNM3diNDRhaWRHRm9LdVY1UUhUSF9HUHZMNTRmS1dpaURFVEE5ZXN1ZG5BaEJrVHVNQUFKSXNvRmF5aW9CWHRxbldjWjkzVmMtMVZ3c0IwZldacFFGODZLVW41YmdYYkhjQzVjbmhVWUhBY25Fb1R4dXhBR0NHSU9XWExZRFJ1ak9BbF9lcnVqR0JUd08zOENXRGg4ZkRaS01MMG9ha3k4NVJYeEJMaTlpUHc5Y3RFUmRjUTVjcjROSk5CMERQMkhOQUFtcUF0RFFUbmx1ZzRLQnktc1IybTVUTzFkZC1KMTFYMmcwcmRDSEx4VlpCR3Z0SDV5V0hjRXF2TVExV3FUT0dxUEFiTU9nNjVkekVLN09LU2d6WnZnc2d4OFV3bjFLaVM1bEVjRzVDUWJkQWJ4ZmE3aWIyTk8zeDdqel81OS1acmpLUE15NUV3dzNMbEQybG1HQlU2bk5UMU5Vb1BpZ09tTF9nODZGUlR2c0V1d0ZiRVhYS0NhUmgtdlg5NTdnQlJBMHVCek1qOUxnVVdyNzd6dW0tdGxPREIzaF9DNXhaZWlZQjd1U0JQNTZFelA2WkhGVW9CaXdzMERjaFl3eDFzcW1iNWxEZHZwdWhQa3A0UmxYTGw0Tlc1XzlkTUh0TkxpajFKZmpHNE5jTTNCN1FLLXNYUVQ0cDlSYWFyZ1VqZW1VamxWa3I3TEM0bEQxWHk5VE1nRVZvcUMxcUxxVmZWUzlNejBfRFpJdV91bVlIN0oyekNnVGV1dW1feFlGTWVqeHVGNVJnaHo0TG9vZVZXSmFIV3JkZU9kMDQ1QXN6TEtZRWc4MjJpdlVGM0gyM19SNm5HSDh5NkVTdEktZVZBa1RlLTZKUTAtaXRPVzVvamNrMjZzY1FXRVVRMmtQMlJkS3Z5YTB0cnVfamFjbElNZWZ5WjY5NExsLVM2Q3lDTHZCcnVsSXVEUXVPTUlYUW5JOTFpeDdYQkJYajQxUnF4RXpEWlBDdHBXNTRLNHh5OW1iMUdpMGFqc2gweGhHV3A0SlYzWTRhQzRxekJ1TEhLR0IzbXBYRExITlhXcWppb24wS0JhYTBQLXFEVEFkTGVPRzdSUUc0VjZibTNEbHkxVnlkNzV1SDBrTTdPZmxRbU1hQ3lMR2c3ODRxMFRrcjV4VFlpWXlXUHh3eTFuNy1mTWRqOWxnak1DeEtsaDZYRTBYM01ib0tmMDM5bzhQMjktNEdkVmJYVjlwcERuSDVuTTV2VFJFSS05UWh5SF9XckItaDY3eFdTQ2lnYVZrMEp5Tm9iVkNfNFZpbTE4QjR4VV9iQnJKZGk3eVY4TWotLXU0dUQ2WmxjcDVqZ28tZjR0RGFoMEQ1T0JFZUE1UF9pZUpVNGt6Q0o0c3NHQVQ5Q3NKZ0pzNzlFdDc5RnBwVXRSOWE5RzY1eVhNZFl2LW4xV0NEVGNPZXVua3hTZnloTmk5V1RoVW1CY0lhSkE2eVNKQVJEYTN3RGk1cUNBYUZMWFZuN1dQVm5US2Y1bktUOFVhbzdQNTFrOC05cmJDcEhxQUh5QkJSSER4U0FaclVkS2xiamRRc2RncVdrNlFlX2E5WFRMSEJKU1pVYk9Ud0ExeW95WlhmNERiQTd5VjYxY1A4SXlvMU5QMkJub3JaNnJ3MENqbUNjakZaRUduNTZVU0N2cnVQTl93VWc3TEVIYlBJVzBYQkJxdUFnYmw5NjhvcHM5OURkZUI4MGQ0NDhoQWxldkhCUXR2emhOem0xc0FQSE5XSE9VYnQwU1RMV2M4ZWN5cHdTd2kxWHpGX3lCcHAzUlVhN3VTcmgyS2c2Q01KSXlOaUZqNnpta0JkMWtkOWxHSkNlc3hNVFBlbEQ3bTZZeXpYd2VzM2g4cF91V3Y5RnQ0aEM4a1pmNHppS0Z2QWs3dDY3Rm1BZjEyWFc3WVBkdGw2ZXZrWURfQ1dmbzI2bi0wc0ZvNU5QVlJVQ00xUXJkaUdyWGJPWXFmcUdvZWNrVFR2ek53M1J1aXVYSFUyNkx4dlVCZ28yZWk1NXNwZTlYWWZuMm90U2FqaXdVcld4N3RYeEtNZl9jV1p5U2dudnpJNGZkdTlCUG9xUndzSkdVY2k0WVRqaFpQYU9lcFIwRy13V0FkNGJ2TUxQVXVicWRGbFhtQm1SSVNOMkc1YjBuQVdCcDV0eVZPUFpaRVlBNWdKY1lOdFE3d3V5U1g5cDEzQ0l1SmcyWTYzUk5rN21OU05MampSSXk1dTNPMmRoNmZjMVlabUQyXy1tMXFkNXVoS3ZWei1pdHVQbW5Tb1h3RHAtdDMxWGFHaUhKaVhxND0=) # <-- Put your encrypted keystore file here
        CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmcwai1JYlZtM0g5NXgtMzJTOHh4aDd1Ri1XMzBtLWVGVjBQRnR2VzdqMUoyTFVPMjhaenZIbmE0dFlVOEt1QllXZjBWWGZXQzBtTHkyY0FDWGIxdGQzUEtaQWc9PQ==) # <-- Put your encrypted keystore password here
        CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmcwai1JYlZtM0g5NXgtMzJTOHh4aDd1Ri1XMzBtLWVGVjBQRnR2VzdqMUoyTFVPMjhaenZIbmE0dFlVOEt1QllXZjBWWGZXQzBtTHkyY0FDWGIxdGQzUEtaQWc9PQ==) # <-- Put your encrypted keystore alias password here
        CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmcwai05QzUxczRPOFo4c0tHN3p6V2ZsRFlsN2UxMW95TlQtclBnU1kzbzNsNmxvYUFxTmo1OVUwRlpBQWNnWDU2LWpKa0pjYVFTWXBKc05Lc0hNV3pzLTBpaVE9PQ==) # <-- Put your encrypted keystore alias username here
      node: latest
      xcode: 12.2
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: AWS CLI configuration
        script: |
          mkdir ~/.aws
          cat >> ~/.aws/config <<EOF
          [default]
          aws_access_key_id=$AWS_ACCESS_KEY_ID
          aws_secret_access_key=$AWS_SECRET_ACCESS_KEY
          region=$AWS_DEFAULT_REGION
          output=json
          EOF
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/local.properties"
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_ALIAS_PASSWORD
          keyAlias=$CM_KEY_ALIAS_USERNAME
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Build Android debug APK
        script: |
          ./gradlew assembleDebug
      - name: Build Android test APK
        script: |
          ./gradlew assembleAndroidTest
      - name: Run AWS Device Farm test
        script: |
          cd .scripts && ./run_aws_espresso.sh
      - name: Verify Device Farm test
        script: |
          set -e
          set -x
          export AWS_RESULT=$(cat $FCI_BUILD_DIR/.scripts/test-result.json | jq -r '.run.result')
          if [ $AWS_RESULT != "PASSED" ]
          then
            echo "AWS tests did not pass, the result was $AWS_RESULT"
            exit 1
          else
            echo "AWS tests PASSED!"
          fi
      - name: Build Android production release
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - nihal@nevercode.io
        notify:
          success: true
          failure: false